### ISSUE TITLE
receiving no chat messages from Synology chat

### ISSUE THREAD

**Issue by tommyMX** [phoeluga/ioBroker.synochat#12]
Hi, 
I need help because I dont receive any chat message from the Synology chat to the data point in iobroker.

Also this looks strange:

<img width="1432" alt="Bildschirmfoto 2023-08-08 um 21 50 33" src="https://github.com/phoeluga/ioBroker.synochat/assets/36209886/57229154-ec11-4424-92b2-1c33d41ab4fa">

Why are both called outgoing message and not incoming message?

Because my configuration seems right:
<img width="1604" alt="Bildschirmfoto 2023-08-08 um 21 50 45" src="https://github.com/phoeluga/ioBroker.synochat/assets/36209886/4210e177-8910-47d9-8769-058540336162">

**Comment by phoeluga** [comment]
Hi @tommyMX ,

For messages, that will be received by the ioBroker, make sure that the Channel name in the `Synochat` instance configuration is matches the Channel name from Synology chat server. This is important, since this is the identifier to map each other.

Beside that, could you please check if messages will be received by the ioBroker if the message object of the corresponding channel is not `(null)` (just add some random string there)?

About the description:
The channel type (incoming; outgoing) is specified from the perspective of the Synology chat. For example, 'Incoming' means that the messages will be sent to the Synology chat server.

If this is still not working, please provide the debug log output including the start of the adapter instance until the message should be received.
NOTE:

> To get more detailed information about the adapter behaviors in case of issues, you can increase the log level of the synochat adapter instance to debug.
> 
> Since this adapter is using a web adapter instance to provide web hooks to the Synology chat server, the configured web instance is executing some functions. In order to get more detailed information in case of receiving message issues you need to increase the log level of the configured web instance as well to debug. Log messages related to the synochat adapter can be identified by the log message prefix synochat.<INSTANCE_NUMBER>.

Please also provide the information about:
 - Adapter version
 - JS-Controller version
 - Node version
 - Operating system
 

Thanks,
phoeluga

**Comment by tommyMX** [comment]
Hi, wir können auch Deutsch reden... :-)

also das mit incoming verwirrt , denn wenn ich bei den Kanälen sage Get Data dann müsste es doch incoming sein oder?

Outgoing und der weg funktioniert ja wenn ich in den DP was reinschreibe landet es im SynoChat .

Und das Logfile gibt auch keinerlei Fehler aus...

Was mich noch verwirrt sind bzw. dass man Auslöserworte machen muss aber das mache ich auch

Jetzt hier mal ein paar Screenshots:


<img width="1632" alt="Bildschirmfoto 2023-08-11 um 17 49 34" src="https://github.com/phoeluga/ioBroker.synochat/assets/36209886/7ed5182d-f95d-4097-94e2-097cf9289dec">
<img width="1710" alt="Bildschirmfoto 2023-08-11 um 17 47 37" src="https://github.com/phoeluga/ioBroker.synochat/assets/36209886/678aa8f9-9173-4f36-b914-e64a03171b3b">
<img width="1671" alt="Bildschirmfoto 2023-08-11 um 17 47 27" src="https://github.com/phoeluga/ioBroker.synochat/assets/36209886/995258c2-6573-40dc-bcba-a88634d71f9a">
<img width="1684" alt="Bildschirmfoto 2023-08-11 um 17 39 06" src="https://github.com/phoeluga/ioBroker.synochat/assets/36209886/bc00904f-8595-4f98-869b-5b9b871f1be8">
<img width="1715" alt="Bildschirmfoto 2023-08-11 um 17 38 53" src="https://github.com/phoeluga/ioBroker.synochat/assets/36209886/9552dd0d-9f82-4fa9-9ef6-e0b5d87dd374">

**Comment by tommyMX** [comment]
<img width="967" alt="Bildschirmfoto 2023-08-11 um 17 57 04" src="https://github.com/phoeluga/ioBroker.synochat/assets/36209886/d97f0fba-5a8e-473f-a0e4-dbd189bf11a1">

Laut Chat Admin Syn Console geht der Webhook auch raus

**Comment by phoeluga** [comment]
Ich vermute hier eine fehlende initiale Prüfung von Nachrichten, die vom Synology-Chat-Server erhalten werden. Das sehe ich mir grade nochmal an.

Daher die Bitte zu prüfen, ob die Nachricht im Objekt ankommt, wenn der Wert des Objekts nicht null ist. Es ist ausreichend hier irgend einen Wert manuell zu setzen.

Im Logscreenshot sehe ich leider nur die INFO logs. Für genauere informationen, müssen Loglevel der Web-Instanz und der Synochat-Instanz auf DEBUG gestellt werden:
![image](https://github.com/phoeluga/ioBroker.synochat/assets/77971105/71cc76c0-dc98-4512-9bad-bc430089b016)



Zu der Namensgebung:
Die Zuordnung der Kanaltypen muss intern anhand der Synology-Chat-Server typen abgebildet werden. D.h. ein Incoming channel ist ein Synology-Chat-Server incoming channel. Der interne Objekttyp wird dann auch in der Objektbeschreibung angegeben.
Das mag auf den ersten Blick verwirrend sein, ist aber leider technisch notwendig.
Die Beschreibung in der Instanzkonfiguration wurde mit einem Mapping hinterlegt. Ich werde mir für die Objektbeschreibung nochmal ansehen, ob und wie hier ein ähnliches Mapping in der UI realisiert werden kann.

**Comment by phoeluga** [comment]
Grade die Änderungen im Kommentar gesehen.
Die Logausgabe wurde an dieser Stelle in der aktuellen Version 1.3.0 angepasst. Das leere Feld des Channelnamens im Body der Anfrage kann ich aktuell noch nicht nachstellen.

Ich würde daher bitte, das Ganze nochmal mit der Version 1.3.0 zu testen. Hier haben wir zumindest bessere Logausgaben an dieser Stelle.
Die Version ist noch im Beta-Repo, oder kann direkt über GitHub gezogen werden.
Das Problem mit initial leeren Objekten konnte ich identifizieren. Muss gefixed werden.

Als Workaround muss das Objekt initial einmal manuell auf irgend einen Wert `!= null` gesetzt werden.

**Comment by tommyMX** [comment]
hab jetzt mal irgendwas in den DP reingeschrieben...

beide Adapter sind auf DEBUG...verstehe auch nicht warum da nicht mehr raus kommt, hab erst kürzlich die Neue Version von IO gezogen mit nodes 18 etc...

ich glaube auch das Synology Chat auch Problem hat, denn es wird nicht immer ein Webhook Ausgang produziert, das sehe ich in der Admin Chat Konsole unter Protokolle...obwohl ich das Auslöser wort hernehme..

Bin auch gerade auf der 1.3.0 die hatte ich mir heut früh gezogen...

Wie funktioniert bei dir das mit den Auslöser Worte? ich Schreibe halt Test, 12345 Test ist das Wort und es generiert keinen Webhook zumindest nicht immer...

Dachte Anfangs es ist ein problem weil der eine Kanal Privat ist, aber bei dem Allgemein gehts ja auch ned wirklich...

<img width="1368" alt="Bildschirmfoto 2023-08-11 um 18 51 23" src="https://github.com/phoeluga/ioBroker.synochat/assets/36209886/30fd3ea9-b489-45b5-b85f-56c6263c33aa">
<img width="1407" alt="Bildschirmfoto 2023-08-11 um 18 51 19" src="https://github.com/phoeluga/ioBroker.synochat/assets/36209886/304540b4-3ae6-42ba-b67e-8bb0eea91522">
<img width="1679" alt="Bildschirmfoto 2023-08-11 um 18 51 03" src="https://github.com/phoeluga/ioBroker.synochat/assets/36209886/c081380c-d3f2-4dbc-a48e-c547ef68de7f">

**Comment by tommyMX** [comment]
<img width="1744" alt="Bildschirmfoto 2023-08-11 um 18 56 29" src="https://github.com/phoeluga/ioBroker.synochat/assets/36209886/7f9f10c1-d909-442c-8793-97af4056cfbc">

**Comment by tommyMX** [comment]
Also die zweite Nachricht kam wieder nicht durch, würde ja glatt meinen dass der Webhook im Synchat nicht wirklich funktioniert....?

**Comment by phoeluga** [comment]
Wichtig ist noch zu bemerken, dass die Channelnames bei Nachrichten, die vom Synology-Chat-Server zum ioBroker gesendet werden GENAU übereinstimmen. Das Mapping was hier stattfindet ist casesensitive (Groß- und Kleinschreibung beachten).

Den Screenshots zu Folge war das initiale Problem dieser Bug #13.

Die Trigger Words des Synology-Chats kann ich auch nur im gewissen Maße nachvollziehen. Zumindest eine Wildcard-Möglichkeit wäre hier wünschenswert. Ich werde hier auch mal ein Featurerequest bei Synology anlegen.

**Comment by tommyMX** [comment]
okay also über den Test Kanal läuft es und ein Test, ist nicht das gleiche wie Test , zumindest geht das jetzt mal aber ich gebe dir recht eine Wildcard wäre da gut, verstehe nicht warum die da eine Unterscheidung mit dem Auslöserwort machen denn bei dem Umkehr weg was man von IO über den DP nach SynoChat schickt, geht ja auch alles durch und bei der WEbhook Konfiguration Incoming gibts ja dieses Auswahlfeld nicht

**Comment by phoeluga** [comment]
Guter Hinweiß, das konnte ich auch schon feststellen.
Das Trigger-Word MUSS alleine stehen 🙄 
Ich werde die Findings aus diesem Ticket entsprechend in der Doku ergänzen.

Die neue Version (voraussichtlich 1.3.1), die dann auch #13 beinhaltet, wird dann in den kommenden Tagen veröffentlicht.

**Comment by tommyMX** [comment]
Danke dir :-)
