### ISSUE TITLE
Feature Request: Add Adapter to iobroker.notifications

### ISSUE THREAD

**Issue by Ilovegym66** [phoeluga/ioBroker.synochat#9]
Add Adapter to iobroker.notifications, please.
See https://github.com/foxriver76/ioBroker.notification-manager/issues/4#issuecomment-1637652942

**Comment by phoeluga** [comment]
Changes have been implemented as far as possible. Unfortunately, in initial tests it was not possible to receive messages from Notification Manager because the instance crashed.
-->  In clarification

**Comment by phoeluga** [comment]
New features are working. Specially the Notification-Manager integration is required to work with JS controller >=5.0.8 !

-----

- [x] Pipeline green
- [ ] Final tests before release
(Pending)
- [x] Release version candidate specified
(v.1.3.0)

**Comment by phoeluga** [comment]
@Ilovegym66 The integration was implemented and tested. To have a user defined way to send data from the Notification-Manager to the Synology chat, message templates were introduced. Please have a look in the Readme for details and let me know any finding.

**Comment by Ilovegym66** [comment]
Well done!
